databases:
  - name: tipdoor
    plan: free
    databaseName: tipdoor
    user: tipdoor

services:
  - type: web
    plan: free
    name: tipdoor
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tipdoor
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4