# Generated by Django 5.2.4 on 2025-11-18 16:33

from django.db import migrations

def populate_mobile_numbers(apps, schema_editor):
    Customer = apps.get_model("shop", "Customer")
    counter = 1
    for customer in Customer.objects.all():
        customer.mobile_number = f"999000000{counter}"
        counter += 1
        customer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_customer_mobile_number_alter_customer_email'),
    ]

    operations = [
        migrations.RunPython(populate_mobile_numbers),
    ]
